database:
  host: 10.10.106.159
  port: 3306
  username: su01
  password: su01
  name: operator360
  tables:
    feature_registry: features
    signal_registry: signals
    opt_registry: opt_master

rocksdb:
  host: 10.10.79.28
  port: 30524
  endpoint: /sid/batch_get