database:
  host: 10.10.75.181
  port: 3306
  username: su01
  password: su01
  name: data_platform
  tables:
    feature_registry: opt360_features
    signal_registry: opt360_signals
    opt_registry: opt_master
rocksdb:
  host: 10.10.79.28
  port: 30524
  endpoint: /sid/batch_get
