apiVersion: v1
kind: Service
metadata:
  name: operator360-api
  namespace: strot-applications
  labels:
    app: operator360-api
    env: prod
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: operator360-api
    env: prod
